### ISSUE TITLE
Format issue

### ISSUE THREAD

**Issue by ice1000** [myjinxin2015/Katas-list-of-Training-JS-series#2]
The last few lines in `README.md` is poorly formatted

**Comment by billbunkum** [comment]
@ice1000 Looks like it's cos there's not a `space` between the `###` and `+`. Also, I love your name! :D

**Comment by ice1000** [comment]
Thanks for loving my name :joy:

**Comment by ice1000** [comment]
Since myjinxin has died on GitHub, this issue will never get replied. Closed
